# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Flying <- function(time, site, x, dep_site) {
    .Call(`_EAAFsdp_Flying`, time, site, x, dep_site)
}

Init <- function(MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend) {
    invisible(.Call(`_EAAFsdp_Init`, MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend))
}

BackwardIteration <- function(pbar) {
    .Call(`_EAAFsdp_BackwardIteration`, pbar)
}

InitSim <- function(MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, y_gain, y_expend, FMatrix, DMatrix1, DMatrix2, PMatrix1, PMatrix2) {
    invisible(.Call(`_EAAFsdp_InitSim`, MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, y_gain, y_expend, FMatrix, DMatrix1, DMatrix2, PMatrix1, PMatrix2))
}

simForaging <- function(f_intensity, time, site, x) {
    .Call(`_EAAFsdp_simForaging`, f_intensity, time, site, x)
}

simFlying <- function(decision, time, site, x) {
    .Call(`_EAAFsdp_simFlying`, decision, time, site, x)
}

forwardSim <- function(Ind, start_time, start_site, start_x) {
    .Call(`_EAAFsdp_forwardSim`, Ind, start_time, start_site, start_x)
}

